[build]
builder = "nixpacks"
nixPkgs = ["nodejs_18", "python311", "pip"]
buildCommand = """
  echo "Installing Frontend Dependencies" &&
  cd frontend && npm ci && npm run build &&
  echo "Installing Backend Dependencies" &&
  cd ../backend && pip install --no-cache-dir -r requirements.txt
"""

[deploy]
startCommand = "cd backend && gunicorn app:app"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
