[build]
builder = "nixpacks"
nixPkgs = ["nodejs_18", "python311", "pip"]
buildCommand = """
  cd frontend && npm install && npm run build &&
  cd ../backend && pip install -r requirements.txt
"""

[deploy]
startCommand = "cd backend && gunicorn app:app"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
